### ISSUE TITLE
Consider _projr.yml configuration again

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#260]
```[tasklist]
### Tasks
- [ ] https://github.com/SATVILab/projr/issues/270
- [ ] https://github.com/SATVILab/projr/issues/269
- [ ] #266 
- [ ] https://github.com/SATVILab/projr/issues/272
- [ ] #265 
- [ ] #267 
- [ ] #268
- [ ] https://github.com/SATVILab/projr/issues/276
```

So, at the moment we have that only directories depend on the profile. Other settings we have that are context-dependent are:
- what is saved to output depends on version
- What is uploaded to GitHub depends on branch and version

I suppose we can make everything depend on a cue:
- branch
- profile
- version

People can then add a named list beneath if they want, OR a single entry that is either logical (true) or character (always/never, or version) or else a list (specifying branch, )

I suppose for projr_dev, we may want to have that as local settings. 

Ya, that makes a lot of sense - have `_projr_dev.yml` as a local file and `_projr.yml` as an any-system file. 
It would be annoying to develop on different computers, but I guess that's just the price.
