### ISSUE TITLE
Add various OSF directory structures

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#440]
```[tasklist]
### Tasks
- [ ] https://github.com/SATVILab/projr/issues/441
- [ ] https://github.com/SATVILab/projr/issues/442
- [ ] https://github.com/SATVILab/projr/issues/443
- [ ] https://github.com/SATVILab/projr/issues/444
```

- Options
 - Content-addressable
 - Version-addressable
   - Sub-options
     - On change
     - Always
 - As-is
- Other considerations:
  - Automatic archiving structure?
    - Well, we can make it version-addressable (at least for now, perhaps a good default). But where exactly?
- source:
  - remote_structure:
    - function: structure of OSF directory
    - options: latest, version, content 
      - latest: everything in there is what you should have
      - version: each thing is versioned according to the overall project version
      - content: content-addressable
  - download options:
    - cue:
      - function: triggers to cue automatic download
      - options: major, minor, build, on_change, manual (default)
    - sync_approach:
      - function: how we choose what to download
      - options: delete_then_download_all, download_all (default), download_missing
    - conflict:
      - function: what to do if there is a file there already
      - options: overwrite (default), skip, error
  - upload:
    - cue:
      - function: triggers to cue automatic download
      - major, minor, build, on_change (should be default), manual
    - sync_approach:
      - function: how we choose what to upload and to handle what' there already
      - options: delete_then_upload_all, upload_all, missing_only, changed_only
    - version_source:
      - function: how we decide what has changed
      - options: manifest
    - conflict:
      - same as for download, just in reverse
