### ISSUE TITLE
Version data

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#51]
### Tasks
- [ ] Delete old data
- [ ] Check if data have changed
- [ ] Say (optionally) how data have changed (e.g. number of rows etc.)
