### ISSUE TITLE
Figure out if and how to link commits to project versions

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#53]
### Tasks

- [ ] Consider if we can reasonably do this (e.g. even if the main branch is merged later)
- [ ] Consider how best to do this
- [ ] Consider how to output this into a log file appropriately
