### ISSUE TITLE
Identify, evaluate and propose caching methods

### ISSUE THREAD

**Issue by MiguelRodo** [SATVILab/projr#57]
### Tasks

- [ ] Evaluate knitr's cache option
- [ ] Evaluate Frank Harrell's [`runIfChanged` function](https://hbiostat.org/rflow/caching.html)
- [ ] Evaluate Quarto's freeze option
- [ ] Evaluate creating a separate package for data processing
- [ ] Evaluate `targets`
